- hosts: bastion
  tasks:
    - include_vars:
        file: vars.yml
    - ping:
    - pkgng:
        name: openssh-portable
    - user:
        name: "{{ user }}"
    - template:
        src: sshd_config_bastion
        dest: /etc/ssh/sshd_config
        validate: /usr/sbin/sshd -t -f %s
        backup: yes
    - authorized_key:
        user: "{{ user }}"
        key: "{{ bastion_ssh_key }}"
        exclusive: true
    - authorized_key:
        user: root
        key: "{{ bastion_ssh_key }}"
        exclusive: true

- hosts: clients
  tasks:
    - include_vars:
        file: vars.yml
    - ping:
    - apt:
        name: openssh-server
    - user:
        name: "{{ user }}"
    - template:
        src: sshd_config_client
        dest: /etc/ssh/sshd_config
        validate: /usr/sbin/sshd -t -f %s
        backup: yes
